site_name: Fakelake Documentation
site_url: https://soma-smart.github.io/Fakelake/
site_author: SOMA
site_description: Documentation about FakeLake, a command line tool that generates fake data from a YAML schema.

repo_name: soma-smart/Fakelake
repo_url: https://github.com/soma-smart/Fakelake
edit_uri: edit/main/docs/

extra:
  homepage: https://github.com/soma-smart/Fakelake
  company: https://www.linkedin.com/company/soma-smart/

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
  custom_dir: docs/overrides

nav:
  - 'Home': 'index.md'
  - 'Usage':
    - 'usage/create_your_yaml_file.md'
    - 'usage/generate.md'
  - 'Columns':
    - 'Providers':
      - 'columns/providers/constant.md'
      - 'columns/providers/increment.md'
      - 'columns/providers/person.md'
      - 'columns/providers/random.md'
    - 'columns/options.md'
  - 'Output':
    - 'output/parameters.md'
      